### ISSUE TITLE
Compiling with Visual C++ 2015: strcasecmp is missing

### ISSUE THREAD

**Issue by FilipGh** [Kortforsyningen/PROJ-JNI#28]
I tried to compile the C++ part under Windows, with Visual C++ 2015 compiler.
I followed the "cmake steps" as suggested in src/main/cpp/CMakelists.txt.
One symbol is not defined in bindings.cpp with Visual Studio compilers : strcasecmp.

I added a few lines (specific for VS compiler) to define it:
`#define strcasecmp _stricmp`

Attached is "git --diff" patch

[strcasecmp.zip](https://github.com/Kortforsyningen/PROJ-JNI/files/4016062/strcasecmp.zip)

**Comment by desruisseaux** [comment]
Patch has been integrated in master branch (thanks!). A [1.0-RC4](https://github.com/Kortforsyningen/PROJ-JNI/releases/tag/1.0-RC4) release candidate has been published.
