### ISSUE TITLE
Error while loading proj-binding.dll in Eclipse RCP development environment

### ISSUE THREAD

**Issue by FilipGh** [Kortforsyningen/PROJ-JNI#31]
We bumped into a problem while loading **proj-binding.dll** in our "_Eclipse RCP development_" environment (although, the run time executable runs correctly).

In methode **NativeResource::libraryPath()**, the resource file is given by :
`final URL res = NativeResource.class.getResource(nativeFile);`
The problem is:
- It is NOT of the form : jar:file:/xxxx/yyyy/proj-binding.dll.
- It is something like : bundleresource://92.fwk293907205:3/org/kortforsyningen/proj/proj-binding.dll

Thus, the call to `Paths.get(res.toURI())` throws an exception:
java.nio.file.FileSystemNotFoundException

The proposed patch solves the problem. It runs fine in the following contexts :
* "Normal" context when I compile the simple test : TransformPoints.java
* "Eclipse RCP development" context

Our environment:
* Windows 10
* JAVA 8 64 bits
* Eclipse RCP Luna 4.4.1

**Comment by FilipGh** [comment]
[NativeResource.java.diff.zip](https://github.com/Kortforsyningen/PROJ-JNI/files/4184715/NativeResource.java.diff.zip)

**Comment by desruisseaux** [comment]
Published a new release candidate: https://github.com/Kortforsyningen/PROJ-JNI/releases/tag/1.0-RC5
Thanks for the fix!

Note: given all the nice patches you sent, would you like commit right to this repository?
